### ISSUE TITLE
Could not find gem 'be_gateway' in rubygems repository

### ISSUE THREAD

**Issue by mario-amazing** [begateway/client_ruby#62]
With config from readme:
```ruby
gem 'be_gateway'
```
I have this error:

```
Could not find gem 'be_gateway' in rubygems repository https://rubygems.org/
or installed locally.
```

**Comment by shveikus** [comment]
Hi @mario-amazing 
Good notice! We have to update the readme, cause gem is not hosted on RubyGems.
Nevertheless, you could define source from github in your Gemfile like this:
```ruby
gem 'be_gateway', tag: '1.0.3', git: 'https://github.com/begateway/client_ruby.git'
```

**Comment by mario-amazing** [comment]
Nice, could you update Readme? @shveikus
